server:
  http_listen_port: 3000
  grpc_listen_port: 0

positions:
  filename: "local/positions.yml"

client:
  url: http://loki.service.consul:3100/loki/api/v1/push

scrape_configs:
- job_name: traefik
  static_configs:
  - labels:
      source: "ingress"
      __path__: "/alloc/data/access.log"
  pipeline_stages:
    - json:
        expressions:
          time: time
          level: level
          method: RequestMethod
          status: DownstreamStatus
          path: RequestPath
    - labels:
        method:
        status:
    - timestamp:
        source: time
        format: "RFC3339"
    - drop:
        source: path
        expression: "/ping"
    - drop:
        source: path
        expression: "/metrics"
