entryPoints:
  http:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 15
        graceTimeOut: 10
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 15
        graceTimeOut: 10
    http:
      tls:
        domains:
          - main: "nahsi.dev"
            sans:
              - "*.nahsi.dev"

  traefik:
    address: ":8080"

ping:
  entrypoint: traefik

metrics:
  prometheus:
    entrypoint: traefik

accessLog:
  filePath: "/alloc/data/access.log"
  format: json

providers:
  consulCatalog:
    prefix: "ingress"
    exposedByDefault: false
    endpoint:
      address: "host.docker.internal:8500"
  file:
    filename: "local/traefik/tls.yml"
