apiVersion: 1
deleteDatasources: []
datasources:
  - name: "VictoriaMetrics"
    type: "prometheus"
    url: "http://127.0.0.1:8428"
    isDefault: true
    basicAuth: false
    jsonData:
      timeInterval: "10s"
      manageAlerts: false

  - name: "Loki"
    type: "loki"
    url: "http://127.0.0.1:3100"
    basicAuth: false
    jsonData:
      maxLines: 1000
