apiVersion: 1
deleteDatasources: []
datasources:
  - name: "VictoriaMetrics"
    type: "prometheus"
    url: "https://victoria-metrics.service.consul"
    isDefault: true
    basicAuth: false
    jsonData:
      timeInterval: "10s"
      manageAlerts: false

  - name: "Loki"
    type: "loki"
    url: "https://loki-query-frontend.service.consul"
    basicAuth: true
    basicAuthUser: "${LOKI_USERNAME}"
    jsonData:
      maxLines: 1000
      manageAlerts: false
      tlsAuthWithCACert: true
    secureJsonData:
      basicAuthPassword: "${LOKI_PASSWORD}"
      tlsCACert: |
{{ with secret "pki/issue/internal" "common_name=*.service.consul" -}}
{{ .Data.issuing_ca | indent 8 }}{{ end }}
