scope: postgres

bootstrap:
  pg_hba:
    - "host replication repl 0.0.0.0/0 md5"
    - "host all all 0.0.0.0/0 md5"

  initdb:
    - encoding: UTF8
    - data-checksums

restapi:
  listen: 0.0.0.0:{{ env "NOMAD_PORT_patroni" }}

consul:
  host: {{ env "attr.unique.network.ip-address" }}
  port: 8500
  register_service: true

postgresql:
  listen: "0.0.0.0:5432"
  data_dir: "/data/patroni/"
  remove_data_directory_on_diverged_timelines: true
  parameters:
    # https://vadosware.io/post/everything-ive-seen-on-optimizing-postgres-on-zfs-on-linux/
    full_page_writes: "off"
    wal_init_zero: "off"
    wal_recycle: "off"
