scope: postgres

bootstrap:
  pg_hba:
    - "host replication repl 0.0.0.0/0 md5"
    - "host all all 0.0.0.0/0 md5"

  initdb:
    - encoding: UTF8
    - data-checksums

restapi:
  listen: "0.0.0.0:8008"
  cafile: "/secrets/certs/CA.pem"
  certfile: "/secrets/certs/cert.pem"
  keyfile: "/secrets/certs/key.pem"
  verify_client: "optional"

consul:
  host: "172.17.0.1"
  port: 8500
  register_service: true

postgresql:
  listen: "0.0.0.0:5432"
  data_dir: "/data/patroni/"
  remove_data_directory_on_diverged_timelines: true
