global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
        labels:
          instance: {{ env "attr.unique.hostname" }}

  - job_name: "grafana"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "grafana"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__meta_consul_service_metadata_metrics"]
        target_label: "__address__"
        regex: "(.*)"
        replacement: "$1"

  - job_name: "traefik"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "traefik-internal"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "ingress"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "ingress"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "telegraf"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "telegraf"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__meta_consul_tags"]
        regex: ".*,([^=]+)=([^,]+),.*"
        replacement: "$2"
        target_label: "$1"

  - job_name: "promtail"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "promtail"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__meta_consul_service_metadata_sidecar_to"]
        regex: "(.*)"
        replacement: "$1"
        target_label: "sidecar_to"

  - job_name: "loki"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "loki"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "consul"
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "telegraf"
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):.*"
        replacement: "$1:8500"
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "envoy"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "envoy"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
    metric_relabel_configs:
      - source_labels: ["__name__"]
        regex: "(envoy_cluster_upstream_rq_connect_fail|envoy_http_downstream_rq_no_route|envoy_cluster_upstream_rq_completed|envoy_http_downstream_rq_completed|envoy_cluster_upstream_rq_time_bucket|envoy_http_downstream_rq_time_bucket|envoy_cluster_upstream_rq_xx|envoy_http_downstream_rq_xx|envoy_listener_http_downstream_rq_xx|envoy_cluster_upstream_cx_connect_fail|envoy_tcp_downstream_cx_no_route|envoy_cluster_upstream_cx_rx_bytes_total|envoy_cluster_upstream_cx_tx_bytes_total|envoy_tcp_downstream_cx_tx_bytes_total|envoy_tcp_downstream_cx_rx_bytes_total)"
        action: keep

  - job_name: "unpoller"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "unpoller"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "transmission-exporter"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "transmission-exporter"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "jellyfin"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "jellyfin"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "postgres"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "postgres-exporter"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "zookeeper"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "zookeeper"
        tags:
          - "metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "kafka"
    consul_sd_configs:
      - server: "http://consul.service.consul:8500"
        services:
          - "kminion"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "minio-job"
    bearer_token: '{{ with secret "secret/minio/prometheus" }}{{ .Data.data.token }}{{ end }}'
    metrics_path: "/minio/v2/metrics/cluster"
    scheme: "https"
    static_configs:
      - targets:
         - "s3.nahsi.dev"
