global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets:
        - localhost:9090
      labels:
        instance: {{ env "attr.unique.hostname" }}

  - job_name: "grafana"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "grafana"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "traefik"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "traefik"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "ingress"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "ingress"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "telegraf"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "telegraf"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__meta_consul_tags"]
        regex: ".*,([^=]+)=([^,]+),.*"
        replacement: "$2"
        target_label: "$1"

  - job_name: "promtail"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "promtail"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__meta_consul_tags"]
        regex: ".*,([^=]+)=([^,]+),.*"
        replacement: "$2"
        target_label: "$1"

  - job_name: "loki"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "loki"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "consul"
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "telegraf"
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):.*"
        replacement: "$1:8500"
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "unpoller"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "unpoller"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "transmission-exporter"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "transmission-exporter"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "jellyfin"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "jellyfin"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "postgres"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "postgres-exporter"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "zookeeper"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "zookeeper"
        tags:
          - "metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "redpanda"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "redpanda"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "kafka"
    consul_sd_configs:
      - server: "http://host.docker.internal:8500"
        datacenter: "oikumene"
        services:
          - "kminion"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
