name="Wild Duck Mail"

title="wildduck-www"

[service]
  # email domain for new users
  domain="nashi.dev"
  # default quotas for new users
  quota=1024
  recipients=2000
  forwards=2000
  identities=10
  allowIdentityEdit=true
  allowJoin=false
  enableSpecial=false # if true the allow creating addresses with special usernames
  # allowed domains for new addresses
  domains=["nahsi.dev"]

  generalNotification="" # static notification to show on top of the page

  [service.sso.http]
    enabled = false
    header = "X-UserName" # value from this header is treated as logged in username
    authRedirect = "http:/127.0.0.1:3000/login" # URL to redirect non-authenticated users
    logoutRedirect = "http:/127.0.0.1:3000/logout"  # URL to redirect when user clicks on "log out"

[api]
  url="http://wildduck.service.consul:8888"
  accessToken=""

[dbs]
# @include "/secrets/config/dbs.toml"

[www]
  host=true
  port=3000
  proxy=false
  postsize="5MB"
  log="dev"
  secret="a cat"
  secure=false
  listSize=20

[recaptcha]
  enabled=false
  siteKey=""
  secretKey=""

[totp]
  # Issuer name for TOTP, defaults to config.name
  issuer=false
  # once setup do not change as it would invalidate all existing 2fa sessions
  secret="a secret cat"

[u2f]
  # set to false if not using HTTPS
  enabled=false
  # must be https url or use default
  #appId="https://127.0.0.1:8080"

[log]
  level="info"
  mail=true

[setup]
  # these values are shown in the configuration help page
  [setup.imap]
    hostname="test"
    secure=false
    port=993
  [setup.smtp]
    hostname="test"
    secure=false
    port=465
