server:
  http_listen_port: 3000
  grpc_listen_port: 0

positions:
  filename: "local/positions.yml"

client:
  url: http://loki.service.consul:3100/loki/api/v1/push

scrape_configs:
- job_name: zookeeper
  static_configs:
  - targets:
      - localhost
    labels:
      app: zookeeper
      __path__: "/alloc/logs/zookeeper.stdout.0"
  pipeline_stages:
    - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}'
    - regex:
        expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) [myid:\d] - (?P<level>.*)  (?P<msg>.*)$'
    - timestamp:
        source: time
        format: 2006-01-02 15:04:05,000
    - drop:
        expression: ".*Processing ruok command from.*"
