redis="redis://redis.service.consul:6379/2"

mongo='mongodb://{{- with secret "mongo/creds/zone-mta" -}}{{ .Data.username }}:{{ .Data.password }}{{ end -}}@mongo-primary.service.consul:27017,mongo-secondary.service.consul:27017/zone-mta?tls=true&tlsCertificateKeyFile=/secrets/certs/mongo.pem&tlsCAFile=/secrets/certs/CA.pem'

# Wildduck users and attachments
users="wildduck-users"
gridfs="wildduck-attachments"
