mongo='mongodb://{{- with secret "mongo/creds/zone-mta" -}}{{ .Data.username }}:{{ .Data.password }}{{ end -}}@mongo-primary.service.consul:27017,mongo-secondary.service.consul:27017/zone-mta?tls=true&tlsCertificateKeyFile=/secrets/certs/bundle.pem&tlsCAFile=/secrets/certs/CA.pem'

# Wildduck users and attachments
users="wildduck-users"
gridfs="wildduck-attachments"

[redis]
  host="master.redis-mail.service.consul"
  port=6379
  db=2
  username='{{ with secret "secret/redis/mail/users/zone-mta" }}{{ .Data.data.username }}{{ end }}'
  password='{{ with secret "secret/redis/mail/users/zone-mta" }}{{ .Data.data.password }}{{ end }}'
