server:
  http_listen_port: 3020

traces:
  configs:
  - name: tempo
    receivers:
      zipkin:
    attributes:
      actions:
      - action: upsert
        key: env
        value: prod
    remote_write:
      - endpoint: tempo.service.consul:9095
        insecure: true
    batch:
      timeout: 5s
      send_batch_size: 100
