mongo='mongodb://{{- with secret "mongo/creds/wildduck" -}}{{ .Data.username }}:{{ .Data.password }}{{ end -}}@mongo-primary.service.consul:27017,mongo-secondary.service.consul:27017/wildduck?tls=true&tlsCertificateKeyFile=/secrets/certs/bundle.pem&tlsCAFile=/secrets/certs/CA.pem'

gridfs="wildduck-attachments"
users="wildduck-users"
sender="zone-mta"
queued="mail"

[redis]
  host="keydb.service.consul"
  port=6379
  db=0
  username='default'
  password='{{ with secret "secret/keydb/users/default" }}{{ .Data.data.password }}{{ end }}'
