mongo='mongodb://{{- with secret "mongo/creds/wildduck" -}}{{ .Data.username }}:{{ .Data.password }}{{ end -}}@mongo-primary.service.consul:27017,mongo-secondary.service.consul:27017/wildduck?tls=true&tlsCertificateKeyFile=/secrets/certs/bundle.pem&tlsCAFile=/secrets/certs/CA.pem'

gridfs="wildduck-attachments"
users="wildduck-users"
sender="zone-mta"
queued="mail"

[redis]
  host="master.redis-mail.service.consul"
  port=6379
  db=3
  username='{{ with secret "secret/redis/mail/users/wildduck" }}{{ .Data.data.username }}{{ end }}'
  password='{{ with secret "secret/redis/mail/users/wildduck" }}{{ .Data.data.password }}{{ end }}'
