title: "nahsi.dev"
subtitle: "Dashboard"
columns: "auto"
connectivityCheck: true
footer: ""

colors:
  dark:
    highlight-primary: "#373B41"
    highlight-secondary: "#282A2E"
    highlight-hover: "#373B41"
    background: "#1D1F21"
    card-background: "#373B41"
    link: "#81A2BE"
    link-hover: "#5A647E"
  light:
    highlight-primary: "#373B41"
    highlight-secondary: "#282A2E"
    highlight-hover: "#373B41"
    link: "#81A2BE"
    link-hover: "#5A647E"

links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/nahsi"
    target: "_blank"

  - name: "Matrix"
    icon: "fas fa-message"
    url: "https://matrix.to/#/@nahsi:nahsi.dev"
    target: "_blank"

  - name: "Telegram"
    icon: "fab fa-telegram"
    url: "https://t.me/nahsi_at_tg"
    target: "_blank"

  - name: "Mail"
    icon: "fas fa-envelope"
    url: "mailto:nahsi@nahsi.dev"
    target: "_blank"

  - name: "Hire me"
    icon: "fa fa-briefcase"
    url: "https://resume.nahsi.dev"
    target: "_blank"

  - name: "Homelab"
    icon: "fa fa-flask"
    url: "#homelab"

services:
  - name: "Media"
    icon: "fa fa-photo-film"
    items:
      - name: "Jellyfin"
        subtitle: "Movies"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/jellyfin.svg"
        url: "https://jellyfin.nahsi.dev"

      - name: "Polaris"
        subtitle: "Music"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/polaris.png"
        url: "https://polaris.nahsi.dev"

      - name: "Calibre"
        subtitle: "Books"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/calibre.png"
        url: "https://calibre.nahsi.dev"

      - name: "Audiobookshelf"
        subtitle: "Audiobooks & podcasts"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/audiobookshelf.png"
        url: "https://audio.nahsi.dev"

  - name: "Services"
    icon: "fa fa-globe"
    items:
      - name: "Webmail"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/roundcube.svg"
        url: "https://mail.nahsi.dev"

      - name: "Libreddit"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/libreddit.png"
        subtitle: "Private front-end for Reddit"
        url: "https://libreddit.nahsi.dev"

      - name: "LLPSI"
        icon: "fa fa-graduation-cap"
        subtitle: "Lingua Latina Per Se Illustrata exercises"
        url: "https://llpsi.nahsi.dev"

  - name: "Filesharing"
    icon: "fa fa-file"
    items:
      - name: "SFTPGo"
        icon: "fas fa-cloud-download-alt"
        url: "https://files.nahsi.dev/sftpgo"

      - name: "Filestash"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/filestash.png"
        url: "https://files.nahsi.dev"

      - name: "MinIO"
        logo: "https://assets.nahsi.dev/file/nahsi-assets/minio.png"
        url: "https://minio.nahsi.dev"
