server:
  http_listen_port: {{ env "NOMAD_PORT_promtail" }}

positions:
  filename: {{ env "NOMAD_ALLOC_DIR" }}/data/positions.yml

clients:
  - url: "https://loki-distributor.service.consul/loki/api/v1/push"
    basic_auth:
      username: "promtail"
      password_file: "/secrets/auth"
    tls_config:
      ca_file: "/secrets/certs/CA.pem"

scrape_configs:
  - job_name: "traefik"
    static_configs:
    - labels:
        source: "traefik"
        instance: {{ env "node.unique.name" }}
        __path__: {{ env "NOMAD_ALLOC_DIR" }}/data/access.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            method: RequestMethod
            status: DownstreamStatus
            service: ServiceName
            path: RequestPath
      - labels:
          service:
      - timestamp:
          source: time
          format: "RFC3339"
      - drop:
          source: path
          expression: "/ping"
      - drop:
          source: path
          expression: "/metrics"
