server:
  http_listen_port: 3000
  grpc_listen_port: 0

positions:
  filename: "local/positions.yml"

client:
  url: http://loki.service.consul:3100/loki/api/v1/push

scrape_configs:
- job_name: traefik
  static_configs:
  - targets:
      - localhost
    labels:
      app: traefik
      __path__: "/alloc/logs/traefik.std*.0"
  pipeline_stages:
    - regex:
        expression: '^time="(?P<time>.*)" level=(?P<level>.*) msg="(?P<msg>.*)"'
    - timestamp:
        source: time
        format: 2006-01-02T15:04:05Z
