# https://github.com/zone-eu/zone-mta/blob/master/config/default.js
name="ZoneMTA"
ident="zone-mta"

user="nobody"
group="nobody"

[log]
level="info"

[pools]
# @include "pools.toml"

[dbs]
# @include "/secrets/zone-mta/secrets/dbs.toml"

[queue]
instanceId='{{ env "NOMAD_ALLOC_NAME" }}'

collection="zone-queue"
gfs="mail"

[dns]
caching=false
nameservers=["1.1.1.1", "8.8.8.8"]

[api]
host="0.0.0.0"
port={{ env "NOMAD_PORT_api" }}
hostname="zone-mta.service.consul"
maildrop=false

[plugins]
# @include "plugins/*.toml"
# @include "/secrets/zone-mta/secrets/loop-breaker.toml"

[smtpInterfaces]
# @include "interfaces/*.toml"
