pandaproxy:
  pandaproxy_api:
    - address: 0.0.0.0
      port: 8082
  advertised_pandaproxy_api:
    - address: redpanda-{{ env "meta.redpanda_node_id" }}.service.consul
      port: 8082

redpanda:
  admin:
    - address: 0.0.0.0
      port: 9644

  kafka_api:
    - address: 0.0.0.0
      port: 9092
  advertised_kafka_api:
    - address: redpanda-{{ env "meta.redpanda_node_id" }}.service.consul
      port: 9092

  rpc_server:
    address: 0.0.0.0
    port: 33145
  advertised_rpc_api:
    address: redpanda-{{ env "meta.redpanda_node_id" }}.service.consul
    port: 33145

  auto_create_topics_enabled: false
  data_directory: /var/lib/redpanda/data
  developer_mode: true

rpk:
  coredump_dir: /var/lib/redpanda/coredump
  enable_memory_locking: false
  enable_usage_stats: true
  overprovisioned: true
  tune_aio_events: false
  tune_ballast_file: false
  tune_clocksource: false
  tune_coredump: false
  tune_cpu: false
  tune_disk_irq: false
  tune_disk_nomerges: false
  tune_disk_scheduler: false
  tune_disk_write_cache: false
  tune_fstrim: false
  tune_network: false
  tune_swappiness: false
  tune_transparent_hugepages: false
