name: jobs

on:
  push:
    branches:
      - "master"
    paths:
      - "!.github"

concurrency:
  group: "jobs-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  infra:
    uses: nahsi-homelab/nomad/.github/workflows/run.yml@master
    with:
      namespace: "infra"

  observability:
    uses: nahsi-homelab/nomad/.github/workflows/run.yml@master
    with:
      namespace: "observability"

  services:
    uses: nahsi-homelab/nomad/.github/workflows/run.yml@master
    with:
      namespace: "services"

  deleted:
    uses: nahsi-homelab/nomad/.github/workflows/stop.yml@master
