name: Deployment plan

on:
  pull_request:
    branches:
      - "master"

concurrency:
  group: "plan-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  infra:
    uses: nahsi-homelab/nomad/.github/workflows/run.yml@add-automation
    with:
      namespace: "infra"

  observability:
    uses: nahsi-homelab/nomad/.github/workflows/run.yml@add-automation
    with:
      namespace: "observability"

  services:
    uses: nahsi-homelab/nomad/.github/workflows/run.yml@add-automation
    with:
      namespace: "services"

  deleted:
    uses: nahsi-homelab/nomad/.github/workflows/stop.yml@add-automation
